name: tvqa
channels:
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.5
  - torchvision
  - cudatoolkit=10.1
  - hdf5
  - h5py=2.10.0
  - jupyter=1.0.0
  - jupyterlab=2.1.2
  - tensorboard=2.1.1
  - tqdm=4.46.0
  - matplotlib
  - pip:
      - pytorch-lightning
      - wandb